module hmg

go 1.23.2

require (
    // External Github Repository
	go.mongodb.org/mongo-driver v1.17.1
	github.com/a-h/templ v0.2.793
	github.com/go-chi/chi/v5 v5.1.0    
	//go.mongodb.org/mongo-driver/bson 
	//go.mongodb.org/mongo-driver/mongo

	github.com/go-chi/chi/v5"  
	github.com/joho/godotenv"
	github.com/justinas/nosurf"
    
	github.com/thedevsaddam/renderer
	go.mongodb.org/mongo-driver/bson
	go.mongodb.org/mongo-driver/bson/primitive
	go.mongodb.org/mongo-driver/mongo
	go.mongodb.org/mongo-driver/mongo/options




    // HMG Repository
    //github.com/MingSkyRocker/HMG/models



)

require (
	dario.cat/mergo v1.0.0 // indirect	
)
